apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: default
  labels:
    app: {{ .Values.appName }}
    env: {{ .Values.env }}
spec:
  replicas: {{ .Values.replicas }}
  {{- if .Values.revisionHistoryLimit }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  {{- else }}
  revisionHistoryLimit: 1
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
      env: {{ .Values.env }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
        env: {{ .Values.env }}
    spec:
      containers:
      - name: app
        image: {{ .Values.imageRepo }}:{{ .Values.imageTag }}
        imagePullPolicy: IfNotPresent
        command: [ "sleep" ]
        args: [ "infinity" ]
        env:
        - name: SHA1_SECRET
          value: {{ .Values.sha1Secret }}
        volumeMounts: []
      volumes: []
