---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
    env: {{ .Values.env }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.appName }}
    env: {{ .Values.env }}
  ports:
  - port: 80
    protocol: TCP
    targetPort: {{ default 3000 .Values.service.targetPort }}
